export const ThemeData = [
  {
    title: "General Sunny",
    link: "http://classifieds.demoflynax.com/?template=general_sunny",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_sunny.webp",
    description: "Bright and cheerful sunny theme",
  },
  {
    title: "Service Rainbow",
    link: "http://services.demoflynax.com/?template=services_rainbow",
    img: "https://www.flynax.ru/files/tpl_thumbnails/service/services_rainbow.webp",
    description: "Colorful design for service providers",
  },
  {
    title: "Realty Rainbow",
    link: "http://realty.demoflynax.com/?template=realty_rainbow",
    img: "https://www.flynax.ru/files/tpl_thumbnails/realty/realty_rainbow.webp",
    description: "Vibrant and attractive real estate",
  },
  {
    title: "Auto Rainbow",
    link: "http://auto.demoflynax.com/?template=auto_rainbow",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_rainbow.webp",
    description: "Captivating auto sales template design",
  },
  {
    title: "General Rainbow",
    link: "http://classifieds.demoflynax.com/?template=general_rainbow",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_rainbow.webp",
    description: "Multicolored general-purpose template theme",
  },
  {
    title: "Клон OLX",
    link: "http://classifieds.demoflynax.com/?template=general_olx",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_olx.jpg",
    description: "OLX-inspired classifieds clone template",
  },
  {
    title: "Pets Nova",
    link: "http://pets.demoflynax.com/?template=pets_nova",
    img: "https://www.flynax.ru/files/tpl_thumbnails/pets/pets_nova.jpg",
    description: "Charming template for pet listings",
  },
  {
    title: "Realty Nova",
    link: "http://realty.demoflynax.com/?template=realty_nova_map",
    img: "https://www.flynax.ru/files/tpl_thumbnails/realty/realty_nova_map.jpg",
    description: "Modern design for real estate listings",
  },
  {
    title: "Realty Nova",
    link: "http://realty.demoflynax.com/?template=realty_nova",
    img: "https://www.flynax.ru/files/tpl_thumbnails/realty/realty_nova.jpg",
    description: "Sophisticated theme for property sales",
  },
  {
    title: "Auto Nova",
    link: "http://auto.demoflynax.com/?template=auto_nova",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_nova.jpg",
    description: "Stylish template for auto dealerships",
  },
  {
    title: "General Nova",
    link: "http://classifieds.demoflynax.com/?template=general_nova",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_nova.jpg",
    description: "New generation of general templates",
  },
  {
    title: "Клон Craigslist",
    link: "http://classifieds.demoflynax.com/?template=general_craigslist",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_craigslist.webp",
    description: "Craigslist clone for online classifieds",
  },
  {
    title: "Heavy Machinery",
    link: "http://auto.demoflynax.com/?template=heavy_wide",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/heavy_wide.jpg",
    description: "Template designed for machinery sales",
  },
  {
    title: "Realty Wide",
    link: "http://realty.demoflynax.com/?template=realty_wide",
    img: "https://www.flynax.ru/files/tpl_thumbnails/realty/realty_wide.jpg",
    description: "Wide layout for real estate listings",
  },
  {
    title: "General Wide",
    link: "http://classifieds.demoflynax.com/?template=general_wide",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_wide.jpg",
    description: "Generously spaced general-purpose template",
  },
  {
    title: "Pets Wide",
    link: "http://pets.demoflynax.com/?template=pets_wide",
    img: "https://www.flynax.ru/files/tpl_thumbnails/pets/pets_wide.jpg",
    description: "Wide template for pet-related listings",
  },
  {
    title: "Auto Wide",
    link: "http://auto.demoflynax.com/?template=auto_wide",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_wide.jpg",
    description: "Spacious design for auto sales",
  },
  {
    title: "Real Estate Map",
    link: "http://realty.demoflynax.com/?template=realty_map",
    img: "https://www.flynax.ru/files/tpl_thumbnails/realty/real-estate-map-search-template.jpg",
    description: "Interactive map for real estate",
  },
  {
    title: "Auto Main Blue",
    link: "http://auto.demoflynax.com/?template=auto_main_blue",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_main_blue.jpg",
    description: "Blue-themed main auto sales template",
  },
  {
    title: "Auto Main Red",
    link: "http://auto.demoflynax.com/?template=auto_main_red",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_main_red.jpg",
    description: "Bold red design for auto template",
  },
  {
    title: "Simple Red",
    link: "http://classifieds.demoflynax.com/?template=general_simple&color=red",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_simple_red.jpg",
    description: "Minimalistic red-themed generic template",
  },
  {
    title: "Simple Green",
    link: "http://classifieds.demoflynax.com/?template=general_simple&color=green",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_simple_green.jpg",
    description: "Clean and simple green design",
  },
  {
    title: "Auto Brand",
    link: "http://auto.demoflynax.com/?template=auto_brand",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_brand.jpg",
    description: "Template focused on automotive branding",
  },
  {
    title: "Auto Modern",
    link: "http://auto.demoflynax.com/?template=auto_modern",
    img: "https://www.flynax.ru/files/tpl_thumbnails/auto/auto_modern.jpg",
    description: "Sleek and contemporary auto design",
  },
  {
    title: "General Modern",
    link: "http://classifieds.demoflynax.com/?template=general_modern",
    img: "https://www.flynax.ru/files/tpl_thumbnails/general/general_modern.jpg",
    description: "Modern look for general website",
  },
];
